name = "teakzc/crunchwrap"
version = "0.1.0"
description = "A powerful ffrostfall/crunchyroll wrapper."
authors = ["teakzc"]
repository = "https://github.com/teakzc/crunchwrap"
license = "MIT"
includes = [
    "LICENSE",
    "src/init.luau",
    "src/**",
    "README.md",
    "pesde.toml",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
crunchyroll = { wally = "ffrostfall/crunchyroll", version = "^0.2.0" }
